#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

TEMPLATE = """// Auto-generated by split-react-workspace.py
{imports}

type Props = {{
{props}
}};

export function {name}({destructure}: Props) {{
  return (
{body}
  );
}}
"""


def load_lines(file_path: Path) -> list[str]:
    return file_path.read_text().splitlines(keepends=True)


def build_component(section: dict, lines: list[str], output_dir: Path) -> None:
    name = section["name"]
    start = section["start"] - 1
    end = section["end"]
    body_lines = lines[start:end]
    strip_indent = section.get("strip_indent", 0)
    normalized = []
    for line in body_lines:
        if strip_indent > 0 and line.startswith(" " * strip_indent):
            normalized.append(line[strip_indent:])
        else:
            normalized.append(line)
    imports = "\n".join(section.get("imports", []))
    props = "\n".join(f"  {prop['name']}: {prop['type']};" for prop in section.get("props", []))
    destructure = ", ".join(prop["name"] for prop in section.get("props", []))
    content = TEMPLATE.format(
        imports=imports,
        props=props,
        name=name,
        destructure=f"{{ {destructure} }}" if destructure else "{}",
        body="".join(normalized).rstrip(),
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / f"{name}.tsx").write_text(content)


def main() -> None:
    parser = argparse.ArgumentParser(description="Split large React workspace sections into TSX components")
    parser.add_argument("file", type=str)
    parser.add_argument("--config", type=str, required=True)
    args = parser.parse_args()

    source_file = Path(args.file)
    config = json.loads(Path(args.config).read_text())
    output_dir = Path(config["output_dir"])
    lines = load_lines(source_file)

    for section in config.get("sections", []):
        build_component(section, lines, output_dir)
        print(f"created: {output_dir / (section['name'] + '.tsx')}")


if __name__ == "__main__":
    main()
